export const GET_SLIDER_ITEMS = "GET_SLIDER_ITEMS";
export const GET_PRODUCTS = "GET_PRODUCTS";
export const GET_PRODUCT_BY_ID = "GET_PRODUCT_BY_ID";
export const HANDLE_SIGNIN_MODAL = "HANDLE_SIGNIN_MODAL";
export const HANDLE_LOGIN_MODAL = "HANDLE_LOGIN_MODAL";
